#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : logutils
Version  : 0.3.3
Release  : 15
URL      : https://pypi.python.org/packages/source/l/logutils/logutils-0.3.3.tar.gz
Source0  : https://pypi.python.org/packages/source/l/logutils/logutils-0.3.3.tar.gz
Summary  : Logging utilities
Group    : Development/Tools
License  : BSD-3-Clause
Requires: logutils-python
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
logutils 0.3.3
==============
The logutils package provides a set of handlers for the Python standard
library's logging package.

%package python
Summary: python components for the logutils package.
Group: Default

%description python
python components for the logutils package.


%prep
%setup -q -n logutils-0.3.3

%build
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python2 setup.py build -b py2 install --root=%{buildroot}
python3 setup.py build -b py3 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
